{% set version = "2.0.1" %}

package:
  name: sdl2_net
  version: {{ version }}

source:
  url:  https://www.libsdl.org/projects/SDL_net/release/SDL2_net-{{ version }}.tar.gz
  sha256: 15ce8a7e5a23dafe8177c8df6e6c79b6749a03fff1e8196742d3571657609d21

build:
  number: 0

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - toolchain
    - sdl2

  run:
    - sdl2

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -f $PREFIX/lib/libSDL2_net.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_net.dylib  # [osx]
    - test -f $PREFIX/lib/libSDL2_net.so  # [linux]
    - test -f $PREFIX/include/SDL2/SDL_net.h  # [unix]
    - if not exist %LIBRARY_LIB%\\SDL2_net.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\SDL2_net.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\SDL_net.h exit 1  # [win]

about:
  home: https://github.com/libsdl-org/SDL_net
  license: ZLIB
  license_file: COPYING.txt
  summary: A simple, cross-platform wrapper over TCP/IP sockets.
  doc_url: https://wiki.libsdl.org/SDL_net
  dev_url: https://github.com/libsdl-org/SDL_net

extra:
  recipe-maintainers:
    - dschreij
