travis:
  secure:
    BINSTAR_TOKEN: UdTRckKQywgP9+f3BuHlArEAl1atkOOGtMlJmGD+3Ssyo1G7FN9nTggM12e62QMk05XjsUSPhCldiJ9GNxaFHr/VYpFtVvoMzYrDg96VaI+FsZDzitPIVbLJy/HNPlSWqZyT/M+vkW6L7Wo/rq+AiB8+/rsVXdr6EdQx9MFCYO/gaIkVyoVsLQ4czKA/oda6hMNAVq3W0VkZIuRbCfTuY4axo34oSKHW5qti8lamtAeEwY2SYrQ3enoEp7KXycmXb9XwvjwTcBl9iuht0cS6wkwyUulL+S26NeNyceinijRK54o5VRkcxyfj+b0ZWcrAEAxrdCnJc9cKHc1J4Z/9jW5H2xWm0hhYUgVfDyyZgFQhyRqvaxcewTz2/A7xw7OgWXLjWQjTbGzglmgQQq4fr/0Ufxk7SLjKtID7pPbg6sOish0ulPfYR5/fEqkkKAIpWi6nOnKJ0NtTeRTkSl15kwor05cKigYYknN68kvRjHSL/9KCxbnNgHbhpz3m8teTloZUaR7Nrl6Kjpa6+AVzIBk93w4+Y8ydR9G1OXFmZgsuUQRmuGcCHrNfvpTx/ng9E+5irTAe/8PLq9DTXDIbUW4Pp2nMefouNMFXzBAgI6DmGRC0u68oKB0fWL4UYt56l3A2ERFlRoTxv4CQbhd11IPVH40kAahxhYfLEnFhnco=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
