travis:
  secure:
    BINSTAR_TOKEN: wp9fe5NlcDuS7UuyUueF5E7CiXWNwDTELNm8cj+hAUpjQl8RYfPCJkNhLs0Ex0yKbKI7ULs2RsLk99mHS0DY8DKUZUKnTzsCBM85NNIzlNxa78gmdX6Grl5umWSYxHEFMxItCGUSbbewe5Pn4kQ8pEfo1b8BgqD85a13M8150Xd1daMnvoEJdIi5eRc3G2pPMTpdnUF7pYqRRB1JnCWAdTPLAGDk5MepphTF9qIrVBjVTGQ9uz9dVBCRAWLAJGDc/UObCslQXcsE3i6LjKMYXKGkO+C9hk30nfhdWU4fTOQzJvA9r0dp/p9DM41W1aAwbfXminHsOUEeDpwlXSS1evu9/OymnBS5L7+nFRxJ0D/WW77qya5660ErcqWwlAL6bMoIlGFfm90XBo8D6JzDgbX0ylqwhFt6eQwX6YgdwB7blzDttG8HQMF5g2XCxCE0w8NomkvHkALJCvr40WOgtVy6okpBctUqbjrYtsEsYwRyHyZgHyDJAnd9Bg4O0gF4Qdw7XcRBF1AzxciM+yQr7pDOBQObys0doRYWSpGMiJv2KfQrIZ/jrjRz5pwHMbz2mtD3AlT9e4QYD8HKCtSkzkIsiY3vo5Ku77899dgBXKU/tkPLKKWeO+zhtDxwxolqsjVdkNGPNQlz6NGPd37cZvx1ry9Ic0rQu4yNLjBmE6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
